services:
  spark-jupyter:
    image: spotify_spark  # Asegúrate de que este nombre coincida con el que usas al construir la imagen
    container_name: spark-jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
      - "8050:8050"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
      - ./dashboard.py:/home/jovyan/work/dashboard.py
    restart: unless-stopped